[profile.default]
src = 'src'
out = 'out'
libs = ['dependencies']
ffi = true

# Compilation
solc_version = "0.8.24"
optimizer = true
optimizer_runs = 10_000
via_ir = true
extra_output_files = ["metadata", "irOptimized"]

# Testing
fuzz = { runs = 256 }
block_timestamp = 1_680_220_800 # March 31, 2023 at 00:00 GMT

[fmt]
line_length = 80
int_types = "short"
number_underscore = "preserve"
ignore = []

[doc]
out = "docs_generated" # Note to not overwrite own docs

# Profile for intense testing
# Run via `FOUNDRY_PROFILE=intense forge t`
[profile.intense]
[profile.intense.fuzz]
runs = 10_000
[profile.intense.invariant]
runs = 10_000

[soldeer]
# See https://github.com/mario-eth/soldeer/blob/main/USAGE.md#configuration
remappings_generate = false
remappings_regenerate = false
remappings_version = false
remappings_location = "txt"

# whether to install sub-dependencies or not. If true this will install the dependencies of dependencies recursively.
recursive_deps = false

[dependencies]
chronicle-std = { version = "2", git = "https://github.com/chronicleprotocol/chronicle-std", rev = "ea9afe78a1d33245afcdbcc3f530ee9cbd7cde28" }
forge-std = "1.9.6"
