name: Solc Version Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: recursive
      - run: yarn install

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install deps
        run: forge soldeer install

      - name: Run Forge tests for each supported solc version
        run: >
          FOUNDRY_PROFILE=ci forge test --use 0.8.24 &&
          FOUNDRY_PROFILE=ci forge test --use 0.8.25 &&
          FOUNDRY_PROFILE=ci forge test --use 0.8.26 &&
          FOUNDRY_PROFILE=ci forge test --use 0.8.27
